paths:
  /api/products:
    get:
      summary: Obtiene todos los productos!!
      tags:
      - Products
      responses:
        "200":
          description: Salio bien
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
    post:
      summary: Crea un producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/createProduct'

components:
  schemas:
    Products:
      type: object
      properties:
        _id: 
          type: ObjectId()
          description: id unico del producto
        title:
          type: String
          description: Descripcion del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description:  Precio del producto
        stock: 
          type: Number
          description: Cantidad de stock
      example:
        _id: 650dcca1b0e42de7bb32202c
        title: mesa
        description: mesa de luz
        price: 500
        stock: 3
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: String
          description: as
        price:
          type: Number
          description: acf
        stock:
          type: Number
          description: adr
      example:
        title: mesa
        price: 500
        stock: 3
